version: '3.7'


services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./spotme/:/usr/src/spotme/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev